export const SIDEBAR = {
  OPEN: "OPEN_SIDEBAR",
  CLOSE: "CLOSE_SIDEBAR",
};


export const VIEW_TYPE = {
  CARDS: "VIEW_TYPE_CARDS",
  LIST: "VIEW_TYPE_LIST",
};

export const CREATE_SUGGESTION = {
  REQUEST: "CREATE_SUGGESTION_REQUEST",
  SUCCESS: "CREATE_SUGGESTION_SUCCESS",
  FAIL: "CREATE_SUGGESTION_FAIL",
};

export const GET_SUGGESTIONS = {
  REQUEST: "GET_SUGGESTIONS_REQUEST",
  SUCCESS: "GET_SUGGESTIONS_SUCCESS",
  FAIL: "GET_SUGGESTIONS_FAIL",
};

export const SUGGESTION_VOTE = {
  REQUEST: "SUGGESTION_VOTE_REQUEST",
  SUCCESS: "SUGGESTION_VOTE_SUCCESS",
  FAIL: "SUGGESTION_VOTE_FAIL",
};

export const SUGGESTION_DRAG = {
  REQUEST: "SUGGESTION_DRAG_REQUEST",
  SUCCESS: "SUGGESTION_DRAG_SUCCESS",
  FAIL: "SUGGESTION_DRAG_FAIL",
};

export const DELETE_SUGGESTION = {
  REQUEST: "DELETE_SUGGESTION_REQUEST",
  SUCCESS: "DELETE_SUGGESTION_SUCCESS",
  FAIL: "DELETE_SUGGESTION_FAIL",
};