export const SIDEBAR = {
  OPEN: "OPEN_SIDEBAR",
  CLOSE: "CLOSE_SIDEBAR",
};


export const VIEW_TYPE = {
  CARDS: "VIEW_TYPE_CARDS",
  LIST: "VIEW_TYPE_LIST",
};

export const CREATE_SUGGESTION = {
  REQUEST: "CREATE_SUGGESTION_REQUEST",
  SUCCESS: "CREATE_SUGGESTION_SUCCESS",
  FAIL: "CREATE_SUGGESTION_FAIL",
};

export const GET_SUGGESTIONS = {
  REQUEST: "GET_SUGGESTIONS_REQUEST",
  SUCCESS: "GET_SUGGESTIONS_SUCCESS",
  FAIL: "GET_SUGGESTIONS_FAIL",
};