export const ADMIN_LOGIN = {
    REQUEST: "ADMIN_LOGIN_REQUEST",
    SUCCESS: "ADMIN_LOGIN_SUCCESS",
    FAIL: "ADMIN_LOGIN_FAIL",
};

export const CREATE_ADMIN = {
    REQUEST: "CREATE_ADMIN_REQUEST",
    SUCCESS: "CREATE_ADMIN_SUCCESS",
    FAIL: "CREATE_ADMIN_FAIL",
};
