export const USER_LOGIN = {
    REQUEST: "USER_LOGIN_REQUEST",
    SUCCESS: "USER_LOGIN_SUCCESS",
    FAIL: "USER_LOGIN_FAIL",
};

export const USER_LOGOUT = "USER_LOGOUT";

export const USER_REGISTER = {
    REQUEST: "USER_REGISTER_REQUEST",
    SUCCESS: "USER_REGISTER_SUCCESS",
    FAIL: "USER_REGISTER_FAIL",
};

export const ADD_USER = {
    REQUEST: "ADD_USER_REQUEST",
    SUCCESS: "ADD_USER_SUCCESS",
    FAIL: "ADD_USER_FAIL",
};

export const LOAD_USERS = {
    REQUEST: "LOAD_USERS_REQUEST",
    SUCCESS: "LOAD_USERS_SUCCESS",
    FAIL: "LOAD_USERS_FAIL",
};

export const CREATE_SCRAPE = {
    REQUEST: "CREATE_SCRAPE_REQUEST",
    SUCCESS: "CREATE_SCRAPE_SUCCESS",
    FAIL: "CREATE_SCRAPE_FAIL",
};

export const LOAD_SCRAPES = {
    REQUEST: "LOAD_SCRAPES_REQUEST",
    SUCCESS: "LOAD_SCRAPES_SUCCESS",
    FAIL: "LOAD_SCRAPES_FAIL",
};

export const CREATE_HOME = {
    REQUEST: "CREATE_HOME_REQUEST",
    SUCCESS: "CREATE_HOME_SUCCESS",
    FAIL: "CREATE_HOME_FAIL",
};

export const GET_HOMES = {
    REQUEST: "GET_HOMES_REQUEST",
    SUCCESS: "GET_HOMES_SUCCESS",
    FAIL: "GET_HOMES_FAIL",
};

export const CREATE_BOARD = {
    REQUEST: "CREATE_BOARD_REQUEST",
    SUCCESS: "CREATE_BOARD_SUCCESS",
    FAIL: "CREATE_BOARD_FAIL",
};

export const GET_BOARDS = {
    REQUEST: "GET_BOARDS_REQUEST",
    SUCCESS: "GET_BOARDS_SUCCESS",
    FAIL: "GET_BOARDS_FAIL",
};

export const GET_BOARD = {
    REQUEST: "GET_BOARD_REQUEST",
    SUCCESS: "GET_BOARD_SUCCESS",
    FAIL: "GET_BOARD_FAIL",
};